# Generated by Django 6.1.1 on 2026-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('species', models.CharField(max_length=50, verbose_name='Espécie')),
                ('age', models.CharField(max_length=50, verbose_name='Idade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Vaga')),
                ('schedule', models.CharField(max_length=100, verbose_name='Horário')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
