# Generated by Django 6.1.1 on 2026-09-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersubscription',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
    ]
